baseURL = 'http://www.armatt.hk/'
languageCode = 'zh-hk'
title = 'Ar Matt Blog'
paginate =  10
[Params]
homePageTitle = "Ar Matt Blog"
homePageSubTitle = "www.armatt.hk"
[taxonomies]
  tag = "tags"
[permalinks]
  article = "/article/:title/"
[security.goTemplates]
  allowActionJSTmpl = true
[outputs]
  home = ["HTML", "JSON"]